SELECT p.REFERENCIA, p.DOCUMENTO, p.NAME, p.SURNAME ,P.DESCRIPCION ,p.fecha , p.valor ,c.total, p.ESTADO, c.franchise ,p.RECIBO_ICEBERG, r.VALOR_PAGADO, (p.VALOR - r.VALOR_PAGADO) AS DIFERENCIA from PORTAL_PAGOS_CUN.ppt_cun_transaccion_pago p
LEFT JOIN PORTAL_PAGOS_CUN.PPT_CUN_DETALLE_RESPUESTA_PAGO r ON r.REFERENCIA = p.REFERENCIA LEFT JOIN PORTAL_PAGOS_CUN.ppt_cun_respuesta_pago c ON c.REFERENCIA = p.REFERENCIA 
WHERE p.DOCUMENTO IN ('1035921913') AND p.FECHA >= TO_DATE ('01-05-2025','DD/MM/YYYY') AND P.ESTADO = 'APPROVED' ORDER BY p.fecha DESC;













